### ISSUE TITLE
Automatic inclusion of plugin-specific configuration

### ISSUE THREAD

**Issue by jmozd** [YOURLS/containers#197]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

When using the YOURLS Docker container via Helm chart, there seems to be no way to automatically include plugin configuration. Only a list of pre-defined env vars are supported, adding more requires replacing the config-docker.php file.

Automatic inclusion of additional config files in a well-known location would allow for easy deployment of plugin-enhanced containers via extra volume mounts.

### Motivation

Automatic container deployment via Kubernetes (i.e. via Helm) is becoming more typical. When doing this, the typical way to specify configuration is via environment variables or by mapping "files" to well-known locations inside the container.

The YOURLS container already has (basic) support for this, for a number of well-known env vars drawn in by config-docker.php. But adding additional configuration requires replacing that file (which can be done via above mapping mechanism).

A more elegant version might be to automatically pull in extra config files (one or more files for each plug-in, via Kubernetes' file mapping ("secret"/"configmap") from config-docker.php. This way, per-plugin configuration is made possible, including re-use of the "get values from Docker env" mechanism already available in config-docker.php

### Describe the solution

- define a well-known location for plug-in config files, i. e. "/var/www/html/user/plugins/config.d"
- extend config-docker.php with
```
foreach ( glob( "/var/www/html/user/plugins/config.d/*.php") as $pluginconfig) {
        include $pluginconfig
}
```
at the end of the file, to include the config files from above well-known location.
- Alternatively, make the location configurable via env var and only run the "foreach" if the location value is set.

**Comment by jmozd** [comment]
see https://github.com/YOURLS/docker/pull/199 for a sample implementation

**Comment by LeoColomb** [comment]
Closing this issue as per discussion on #199.
Configuration can be included with volumes and thus be customized as needed.
As described on the pull request, glob file path inclusion should be used with care.
